---
## MY OWN BOX - CONFIGURATION FILE (YAML)

# Set up a custom port for your cloud
apiPort : 4444

# set the public root in any subpath of the present directory
# subPath : lock

# Do you need localtunnel (default : true)
localtunnel : true

# Subdomain to use with localtunnel. If not defined or not available a random name will be provided
# domain : myownname

# Do you need the ui client (default : true) ?
client : true

# Define here a user list for protected access. Default leaves the server open to anyone
users : 
  - username : user1
    password : alongpasword
    root     : client
#   - username : mememe
#     password : hahahahahaha

# Change the default json web token secret (recommanded) (this is for the cloud itself only, you won't have to remember it)
jwtSecret : writeYourOwnHere

# exclusions filter access to the filesystem based on path name. Those are regexes, so remember to escape your special chars.
exclusions :
  - \/myownbox-config.yml$